# Generated by Django 5.0.6 on 2024-06-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govt_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('Gender', models.CharField(max_length=50)),
                ('total_cases', models.IntegerField()),
                ('cases_names', models.CharField(max_length=100)),
                ('case_durations', models.CharField(max_length=100)),
            ],
        ),
    ]
