# Generated by Django 5.0.6 on 2024-06-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='govt_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
