# Generated by Django 5.0.6 on 2024-06-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_id_alter_user_govt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='case_durations',
            field=models.DateTimeField(),
        ),
    ]
