# Generated by Django 5.0.6 on 2024-06-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='case_durations',
        ),
    ]
